### ISSUE TITLE
Is this still mantained?

### ISSUE THREAD

**Issue by deinok** [siemens/meta-iot2000#112]
Hi @jan-kiszka 
The actual master don't compiles in a debian9-amd64.
Also, seems like there is no support for thud due the fact that meta-intel doesn't give support for intel galileo.

So, my question is if there support from @siemens or better we move to other manufacturers?

**Comment by jan-kiszka** [comment]
Master ran through CI before being pushed, and that CI is based on the docker image kasproject/kas, which is using stretch. But maybe some recent Debian update revealed a sleeping issue. Could you share more details of what you did and the log of the failing build?

Yes, sumo and now thud updates are delayed due to additional work needed after Intel discontinued support of the Quark in their layer, but also because of compatibility issues with other components when updating. It's on the agenda, we are just also busy with a newer hardware revision which will address a number of current issues substantially. If you'd like to contribute to raising the priority of a yocto update for the current hardware, please contact the official product support channel.

However, this is also an open source project. Any contribution to features will be welcome and can help accelerating the development, for everyone.

**Comment by deinok** [comment]
@jan-kiszka It could also be a downstream git change. I mean, bitbake downloads a GIT source based on a branch insted than on a tag, a change on that branch could break all the SO building process.

If its still maintained by siemens i can give a helping hand.
Let me try to debug where the bug is in diferent enviroments.

**Comment by jan-kiszka** [comment]
Bitbake downloads what it has been told, and that is usually a specific hash, sometimes also a tag. If you see a recipe that refers to a branch, this would an exception - or a bug.

**Comment by jan-kiszka** [comment]
Update in #107

**Comment by deinok** [comment]
Closing this in favour of #107
