### ISSUE TITLE
is chmod avaible in the windows powershell with docker? 

### ISSUE THREAD

**Issue by IoTcreator** [siemens/meta-iot2000#142]
Hello there!

Is `chmod` avaible in the windows powershell with docker? 
If i wanted to build kas-docker
( doing this obviously before: `git clone https://github.com/siemens/meta-iot2000` 
and 
`wget https://raw.githubusercontent.com/siemens/kas/master/kas-docker`)
`chmod a+x kas-docker`
it shows me the error that `chmod` isnt found in the windows powershell with docker running. 
Hoping for help. 
Best regards!

**Comment by jan-kiszka** [comment]
Never tried on windows, but you will need a POSIX compatible shell for the kas-docker script plus some additional tools.

Alternative: Try to invoke the kas docker container interactively and run inside the container.

    docker run -it kasproject/kas

And then follow the instructions for the container-free build. Note that the build result, the image, will have to be copied out afterwards in order to flash it to the SD card under Windows.

**Comment by IoTcreator** [comment]
got it! Worked fine! 
Thank you very much for the quick solution!
