### ISSUE TITLE
meta-intel-iot-middleware This layer is no longer maintained

### ISSUE THREAD

**Issue by danielycom** [siemens/meta-iot2000#62]
meta-iot2000/meta-iot2000-example/kas.yml
meta-intel-iot-middleware
> This layer is no longer maintained - the useful recipes that used to be here have now been moved out to other layers (meta-oe, meta-python, meta-networking etc.)

So I dont need it anymore?

**Comment by jan-kiszka** [comment]
We currently pull mraa from there, maybe more, but I was already told that meta-intel-iot-middleware is the wrong place to take it from. Brandon (@arfoll), do we want https://github.com/intel/intel-iot-refkit instead?

**Comment by jan-kiszka** [comment]
Things moved on to meta-oe from meta-openembedded. We will switch when updating to Yocto 2.4, see https://github.com/siemens/meta-iot2000/tree/jan/rocko.

**Comment by arfoll** [comment]
Sorry I missed this - yes pull it from the oe layers, as long as you don't
need java it works well.

On 11 Dec 2017 08:10, "Jan Kiszka" <notifications@github.com> wrote:

Things moved on to meta-oe from meta-openembedded. We will switch when
updating to Yocto 2.4, see https://github.com/siemens/
meta-iot2000/tree/jan/rocko.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/siemens/meta-iot2000/issues/62#issuecomment-350639580>,
or mute the thread

**Comment by jan-kiszka** [comment]
Yeah, we dropped Java long ago - bloated the image and was breaking the build too often.

**Comment by jan-kiszka** [comment]
Resolved in master by going to rocko.
