### ISSUE TITLE
Oracle JDK / JRE

### ISSUE THREAD

**Issue by teozfrank** [siemens/meta-iot2000#9]
As the title suggests, I cannot find anywhere how to install oracle java onto the IOT 2040, it would be nice if the image had it already included or to select what version.

Regards,
Frank.

**Comment by jan-kiszka** [comment]
I strongly suspect that binary-only Oracle Java will not work: The Intel Quark requires applications to be built with special compiler options to work around processor errata. That's why we build everything in Yocto and cannot use a standard distribution.

If the 32-bit non-rpm Linux version you can download from Oracle does not run as-is, you need to use the OpenSDK/JRE that is part of the example image.

**Comment by teozfrank** [comment]
What about this? http://git.yoctoproject.org/cgit/cgit.cgi/meta-oracle-java/

**Comment by jan-kiszka** [comment]
That's just an installer recipe for the binary package. Nothing is built from sources here either.

**Comment by teozfrank** [comment]
> OpenSDK/JRE that is part of the example image.

How do I use this?

**Comment by jan-kiszka** [comment]
Oh, it isn't in fact. It's only used during the build. But you can do this by adding IMAGE_INSTALL_append=" openjre-8" in your local.conf, e.g.

**Comment by jan-kiszka** [comment]
Please reopen if there are further questions.

**Comment by jan-kiszka** [comment]
FWIW, I just had to validate Oracle Java 8 (update 131) on the latest image, and it apparently works fine. Just like OpenJRE, built from sources via Yocto as I described above.

**Comment by teozfrank** [comment]
does that work with an existing build or does that have to be done from a custom build? If that is not the case where is the local.conf located to add that?

**Comment by jan-kiszka** [comment]
We didn't try with current official release but went directly to the development version that is generated from master.

What we did was both unpacking the i586 tarball from Oracle on the device (trivial case) and also hooking up meta-oracle-java for generating a preinstalled image. In the latter case, you will need the master-next branch of http://layers.openembedded.org/layerindex/branch/master/layer/meta-oracle-java/ due to the top-most fix.
